# Generated by Django 6.0.4 on 2026-04-26 18:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва валюти')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код валюти (напр. USD)')),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс купівлі')),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс продажу')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюти',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс купівлі')),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс продажу')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Час збереження')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='currencies.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Знімок курсу дня',
                'verbose_name_plural': 'Знімки курсів дня',
                'ordering': ['-date', 'currency__code'],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
